interface Tutor {
    level: "HIGHER_BEGINNER" | "LOWER_BEGINNER" | string;
    email: string;
    google: string | null;
    facebook: string | null;
    apple: string | null;
    avatar: string;
    name: string;
    country: string;
    phone: string;
    language: string;
    birthday: string;
    requestPassword: boolean;
    isActivated: boolean;
    isPhoneActivated: boolean | null;
    requireNote: boolean | null;
    timezone: number;
    phoneAuth: string | null;
    isPhoneAuthActivated: boolean;
    studySchedule: string;
    canSendMessage: boolean;
    isPublicRecord: boolean;
    caredByStaffId: string | null;
    zaloUserId: string | null;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    studentGroupId: string | null;
    feedbacks: Feedback[];
    id: string;
    userId: string;
    video: string;
    bio: string;
    education: string;
    experience: string;
    profession: string;
    accent: string | null;
    targetStudent: string;
    interests: string;
    languages: string;
    specialties: string;
    resume: string | null;
    rating: number;
    isNative: boolean | null;
    youtubeVideoId: string | null;
    price: number;
    isOnline: boolean;
}
interface Feedback {
    id: string;
    bookingId: string;
    firstId: string;
    secondId: string;
    rating: number;
    content: string;
    createdAt: string;
    updatedAt: string;
    firstInfo: FirstInfo;
}
interface FirstInfo {
    level: string;
    email: string;
    google: string | null;
    facebook: string | null;
    apple: string | null;
    avatar: string;
    name: string;
    country: string;
    phone: string;
    language: string;
    birthday: string;
    requestPassword: boolean;
    isActivated: boolean;
    isPhoneActivated: boolean;
    requireNote: string;
    timezone: number;
    phoneAuth: string | null;
    isPhoneAuthActivated: boolean;
    studySchedule: string;
    canSendMessage: boolean;
    isPublicRecord: boolean;
    caredByStaffId: string | null;
    zaloUserId: string | null;
    createdAt: string;
    updatedAt: string;
    deletedAt: string | null;
    studentGroupId: string | null;
}

export default Tutor;
